### ISSUE TITLE
Because no forum thread: why is ModularFlightIntegrator.dll into RealHeat folder?

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RealHeat#10]
There is no thread to ask ...

**Comment by blowfishpro** [comment]
The forum thread is here FYI: https://forum.kerbalspaceprogram.com/index.php?/topic/115066-113-realheat-minimalist-v43-july-3/

**Comment by Gordon-Dry** [comment]
hmmm

**Comment by blowfishpro** [comment]
@rsparkyc it does look like v4.8 includes the ModularFlightIntegrator DLL.  I don't think this should be the case.

**Comment by raidernick** [comment]
He's right that dll should not be in there, it will cause problems with RF right?
