### ISSUE TITLE
Modular Flight Integrator

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RealHeat#3]
Should we pull this out of the released zip file and just make it a required dependency?

**Comment by PhineasFreak** [comment]
Considering that:

* RH is a required mod for RSS.
* RSS requires Kopernicus.
* Kopernicus requires MFI.
* Kopenicus is usually updated more often than RH, meaning that the dependencies have a higher chance to be updated.

I'd say that removing MFI from the RH redistributions would be OK.
