### ISSUE TITLE
release v4.6 has no files, won't index on CKAN until then

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RealHeat#8]
only source zips no release zip included

**Comment by PhineasFreak** [comment]
@rsparkyc Did you not upload a .zip file with the release?

**Comment by Bornholio** [comment]
Thanks!

**Comment by Bornholio** [comment]
CKAN now listing but as 1.3.1

**Comment by blowfishpro** [comment]
The KSP Version is hard-coded into the NetKAN: https://github.com/KSP-CKAN/NetKAN/blob/1baf17e42a815e63bc00df355d81d9c054b1d619/NetKAN/RealHeat.netkan

This is not a great way of doing it.  Ether the .netkan file should be stored in this repo or it should use a .version file
